apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Postgres
    uid: postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: grafana
    jsonData:
      database: jdd
      sslmode: disable
      postgresVersion: 1700
    secureJsonData:
      password: grafana
